version: '2'
services:
    realtorgogo-app:
        image: realtorgogo
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://realtorgogo-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=RealtorGoGo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    realtorgogo-mongodb:
        extends:
            file: mongodb.yml
            service: realtorgogo-mongodb
